name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build React project
        run: |
          npm install
          npm run build

      - name: Copy build files to EC2 temp folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/*"
          target: "/home/ec2-user/deploy-temp"

      - name: Move files to Nginx and custom project root
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clear existing content
            sudo rm -rf /usr/share/nginx/html/*
            rm -rf /home/ec2-user/colorChangerSJL/*

            # Copy to both locations
            sudo cp -r /home/ec2-user/deploy-temp/* /usr/share/nginx/html/
            cp -r /home/ec2-user/deploy-temp/* /home/ec2-user/colorChangerSJL/

            # Fix permissions
            sudo chown -R nginx:nginx /usr/share/nginx/html

            # Restart server
            sudo systemctl restart nginx

            # Log deployment
            echo "Deployment at $(date)" >> ~/deploy.log
