name: Deploy Static HTML Site to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload static files to EC2 temporary folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "*"
          target: "/home/ec2-user/deploy-temp"

      - name: Deploy to both target directories
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clean old files
            sudo rm -rf /usr/share/nginx/html/*
            rm -rf /home/ec2-user/colorChangerSJL/*

            # Copy new files to both locations
            sudo cp -r /home/ec2-user/deploy-temp/* /usr/share/nginx/html/
            cp -r /home/ec2-user/deploy-temp/* /home/ec2-user/colorChangerSJL/

            # Fix permissions
            sudo chown -R nginx:nginx /usr/share/nginx/html

            # Restart nginx
            sudo systemctl restart nginx

            # Log time
            echo "Deployment at $(date)" >> ~/deploy.log
